const routesData = [
    {
      routeName: "CityA to CityB Express",
      departureCity: "CityA",
      destinationCity: "CityB",
      distance: 120,
      duration: 150,
      price: 800,
    },
    {
      routeName: "CityB to CityC Shuttle",
      departureCity: "CityB",
      destinationCity: "CityC",
      distance: 180,
      duration: 200,
      price: 1000,
    },
    {
      routeName: "CityC to CityD Fast Track",
      departureCity: "CityC",
      destinationCity: "CityD",
      distance: 150,
      duration: 180,
      price: 900,
    },
    {
      routeName: "CityD to CityE Express",
      departureCity: "CityD",
      destinationCity: "CityE",
      distance: 200,
      duration: 220,
      price: 1200,
    },
    {
      routeName: "CityE to CityF Direct",
      departureCity: "CityE",
      destinationCity: "CityF",
      distance: 160,
      duration: 190,
      price: 950,
    },
    {
      routeName: "CityF to CityG Rapid Transit",
      departureCity: "CityF",
      destinationCity: "CityG",
      distance: 140,
      duration: 160,
      price: 850,
    },
    {
      routeName: "CityG to CityH Metro Line",
      departureCity: "CityG",
      destinationCity: "CityH",
      distance: 110,
      duration: 140,
      price: 750,
    },
    {
      routeName: "CityH to CityI Commuter Route",
      departureCity: "CityH",
      destinationCity: "CityI",
      distance: 130,
      duration: 170,
      price: 880,
    },
    {
      routeName: "CityI to CityJ Local Loop",
      departureCity: "CityI",
      destinationCity: "CityJ",
      distance: 90,
      duration: 120,
      price: 700,
    },
    {
      routeName: "CityJ to CityK City Connector",
      departureCity: "CityJ",
      destinationCity: "CityK",
      distance: 100,
      duration: 130,
      price: 720,
    },
    
  ];
  